use libsgutils2 infrastructure changes build on deb 4.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -670,6 +670,9 @@ host_vendor
 host_os
 os_deps
 os_libs
+SGUTILS_LIBS
+HAVE_SGUTILS_TRUE
+HAVE_SGUTILS_FALSE
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -4318,6 +4321,83 @@ _ACEOF
 fi
 
 
+{ echo "$as_me:$LINENO: checking for sg_ll_inquiry in -lsgutils2" >&5
+echo $ECHO_N "checking for sg_ll_inquiry in -lsgutils2... $ECHO_C" >&6; }
+if test "${ac_cv_lib_sgutils2_sg_ll_inquiry+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsgutils2  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char sg_ll_inquiry ();
+int
+main ()
+{
+return sg_ll_inquiry ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_sgutils2_sg_ll_inquiry=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_sgutils2_sg_ll_inquiry=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_sgutils2_sg_ll_inquiry" >&5
+echo "${ECHO_T}$ac_cv_lib_sgutils2_sg_ll_inquiry" >&6; }
+if test $ac_cv_lib_sgutils2_sg_ll_inquiry = yes; then
+  SGUTILS_LIBS="-lsgutils2"; have_sgutils=yes
+else
+  have_sgutils=no
+fi
+
+
+ if test x"$have_sgutils" = xyes; then
+  HAVE_SGUTILS_TRUE=
+  HAVE_SGUTILS_FALSE='#'
+else
+  HAVE_SGUTILS_TRUE='#'
+  HAVE_SGUTILS_FALSE=
+fi
+
+
 # AC_PROG_LIBTOOL
 ac_config_files="$ac_config_files Makefile src/Makefile doc/Makefile"
 
@@ -4435,6 +4515,13 @@ if test -z "${am__fastdepCC_TRUE}" && test -z "${am__fastdepCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_SGUTILS_TRUE}" && test -z "${HAVE_SGUTILS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_SGUTILS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_SGUTILS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5064,11 +5151,14 @@ host_vendor!$host_vendor$ac_delim
 host_os!$host_os$ac_delim
 os_deps!$os_deps$ac_delim
 os_libs!$os_libs$ac_delim
+SGUTILS_LIBS!$SGUTILS_LIBS$ac_delim
+HAVE_SGUTILS_TRUE!$HAVE_SGUTILS_TRUE$ac_delim
+HAVE_SGUTILS_FALSE!$HAVE_SGUTILS_FALSE$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 94; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -5087,7 +5177,7 @@ fi
 
 cat >>$CONFIG_STATUS <<_ACEOF
 cat >"\$tmp/subs-1.sed" <<\CEOF$ac_eof
-/@[a-zA-Z_][a-zA-Z_0-9]*@/!b end
+/@[a-zA-Z_][a-zA-Z_0-9]*@/!b
 _ACEOF
 sed '
 s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g
@@ -5100,8 +5190,6 @@ N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
 ' >>$CONFIG_STATUS <conf$$subs.sed
 rm -f conf$$subs.sed
 cat >>$CONFIG_STATUS <<_ACEOF
-:end
-s/|#_!!_#|//g
 CEOF$ac_eof
 _ACEOF
 
@@ -5355,7 +5443,7 @@ s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 s&@INSTALL@&$ac_INSTALL&;t t
 s&@MKDIR_P@&$ac_MKDIR_P&;t t
 $ac_datarootdir_hack
-" $ac_file_inputs | sed -f "$tmp/subs-1.sed" >$tmp/out
+" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed 's/|#_!!_#|//g' >$tmp/out
 
 test -z "$ac_datarootdir_hack$ac_datarootdir_seen" &&
   { ac_out=`sed -n '/\${datarootdir}/p' "$tmp/out"`; test -n "$ac_out"; } &&
