more scripts/scsi_ch_swp work; FUAB VPD page bit

diff --git a/trunk/scripts/scsi_ch_swp b/trunk/scripts/scsi_ch_swp
--- a/trunk/scripts/scsi_ch_swp
+++ b/trunk/scripts/scsi_ch_swp
@@ -6,119 +6,130 @@
 #
 # Uses sdparm and blockdev utilities.
 #
-# Douglas Gilbert 20130514
+# Douglas Gilbert 20130517
 
 
-rdonly=""
+rdonly="--readonly"
 swp="-1"
 verbose=""
 bdverbose=""
 
 usage()
 {
-  echo "Usage: scsi_ch_swp [-h] [-r] [-s <n>] [-v] <blk_device>"
-  echo "  where:"
-  echo "    -h, --help           print usage message"
-  echo "    -r, --readonly       access <blk_device> read-only"
-  echo "    -s <n>, --set <n>    where <n> is:"
-  echo "                           0  - clear SWP"
-  echo "                           1  - set SWP (i.e. disable writes)"
-  echo "                                (default: read SWP)"
-  echo "    -v, --verbose        more verbose output"
-  echo ""
-  echo "Access the Software Write Protect (SWP) bit in the SCSI control"
-  echo "mode page and if changed adjust the Linux block device (e.g."
-  echo "/dev/sdc) settings accordingly."
+    echo "Usage: scsi_ch_swp [-h] [-s 0|1] [-v] [-w] <blk_device>"
+    echo "  where:"
+    echo "    -h, --help           print usage message"
+    echo "    -s 0|1, --set 0|1    where:"
+    echo "                           0  - clear SWP and set RW mode"
+    echo "                           1  - set SWP and set RO mode"
+    echo "                                (default: read SWP and get RO flag)"
+    echo "    -v, --verbose        more verbose, show commands invoked"
+    echo "    -w, --wr             access <blk_device> read-write when '-s 0'"
+    echo "                         (default: access read-only in this case)"
+    echo ""
+    echo "Access the Software Write Protect (SWP) bit in the SCSI control"
+    echo "mode page and if changed adjust the Linux block device (e.g."
+    echo "/dev/sdc) settings accordingly. If supported, when the SWP bit"
+    echo "is set (1) the device is read-only; when clear (0) the device"
+    echo "is read-write (i.e. its contents can be read and changed)."
+    echo "When no options given it reads SWP and gets blockdev's RO flag."
 }
 
 opt="$1"
 while test ! -z "$opt" -a -z "${opt##-*}"; do
-  opt=${opt#-}
-  case "$opt" in
-    h|-help) usage ; exit 0 ;;
-    r|-readonly) rdonly="-r" ;;
-    s|-set) shift ; let swp=$1 ;;
-    v|-verbose) verbose="-v" ;;
-    vv) verbose="-vv" ;;
-    vvv) verbose="-vvv" ;;
-    *) echo "Unknown option: -$opt " ; exit 1 ;;
-  esac
-  shift
-  opt="$1"
+    opt=${opt#-}
+    case "$opt" in
+        h|-help) usage ; exit 0 ;;
+        s|-set) shift ; let swp=$1 ;;
+        v|-verbose) verbose="-v" ;;
+        w|-wr) rdonly="" ;;
+        vv) verbose="-vv" ;;
+        vvv) verbose="-vvv" ;;
+        *) echo "Unknown option: -$opt " ; exit 1 ;;
+    esac
+    shift
+    opt="$1"
 done
 
-if [ $# -lt 1 ]
-  then
+if [ $# -lt 1 ] ; then
+    echo "Need at least a <blk_device> argument."
+    echo ""
     usage
     exit 1
 fi 
 
-if [ ${verbose} ]
-  then
+if [ ${verbose} ] ; then
     bdverbose="-v"
 fi
 
 if ( which sdparm >/dev/null 2>&1 ) ; then
-  true
+    true
 else
-  echo "sdparm not found"
-  sdparm ${rdonly} ${verbose}
+    echo "sdparm not found"
+    sdparm ${rdonly} ${verbose}
 fi
 
 if ( which blockdev >/dev/null 2>&1 ) ; then
-  true
+    true
 else
-  echo "blockdev not found"
-  blockdev
+    echo "blockdev not found"
+    blockdev
 fi
 
-if [ $swp -lt 0 ]
-then
+if [ $swp -lt 0 ] ; then
     if [ ${verbose} ] ; then
-        echo sdparm --quiet ${rdonly} ${verbose} --get=SWP $1
+        echo sdparm --quiet ${rdonly} ${verbose} --get=SWP=1 $1
     fi
-    sdparm --quiet ${rdonly} ${verbose} --get=SWP $1
-    exit $?
-elif [ $swp = "0" ]
-then
-    if [ ${verbose} ] ; then
-        echo sdparm --quiet ${rdonly} ${verbose} --set=SWP=0 $1
-    fi
-    sdparm --quiet ${rdonly} ${verbose} --set=SWP=0 $1
-    res=$?
-    if [ $res -ne 0 ]
-    then
-        exit $res
-    fi
+    sdparm --quiet ${rdonly} ${verbose} --get=SWP=1 $1
     if [ ${bdverbose} ] ; then
-        echo blockdev --setro ${bdverbose} $1
+        echo "blockdev --getro ${bdverbose} $1"
     fi
-    blockdev --setro ${bdverbose} $1
-    # Need to re-read partition table before --setro takes effect
-    if [ ${bdverbose} ] ; then
-        echo blockdev --rereadpt ${bdverbose} $1
-    fi
-    blockdev --rereadpt ${bdverbose} $1
-elif [ $swp = "1" ]
-then
+    echo -n "blockdev's RO flag: "
+    blockdev --getro ${bdverbose} $1
+elif [ $swp = "0" ] ; then
     if [ ${verbose} ] ; then
-        echo sdparm --quiet ${rdonly} ${verbose} --set=SWP=1 $1
+        echo sdparm --quiet ${rdonly} ${verbose} --clear=SWP $1
     fi
-    sdparm --quiet ${rdonly} ${verbose} --set=SWP=1 $1
+    sdparm --quiet ${rdonly} ${verbose} --clear=SWP $1
     res=$?
-    if [ $res -ne 0 ]
-    then
+    if [ $res -ne 0 ] ; then
         exit $res
     fi
     if [ ${bdverbose} ] ; then
         echo blockdev --setrw ${bdverbose} $1
     fi
     blockdev --setrw ${bdverbose} $1
-    # Need to re-read partition table before --setrw takes effect
-    if [ ${bdverbose} ] ; then
-        echo blockdev --rereadpt ${bdverbose} $1
+    # res=$?
+    # if [ $res -ne 0 ] ; then
+        # exit $res
+    # fi
+    # # Need to re-read partition table before --setro takes effect
+    # if [ ${bdverbose} ] ; then
+        # echo blockdev --rereadpt ${bdverbose} $1
+    # fi
+    # blockdev --rereadpt ${bdverbose} $1
+elif [ $swp = "1" ] ; then
+    if [ ${verbose} ] ; then
+        echo sdparm --quiet ${verbose} --set=SWP $1
     fi
-    blockdev --rereadpt ${bdverbose} $1
+    sdparm --quiet ${verbose} --set=SWP $1
+    res=$?
+    if [ $res -ne 0 ] ; then
+        exit $res
+    fi
+    if [ ${bdverbose} ] ; then
+        echo blockdev --setro ${bdverbose} $1
+    fi
+    blockdev --setro ${bdverbose} $1
+    # res=$?
+    # if [ $res -ne 0 ] ; then
+        # exit $res
+    # fi
+    # # Need to re-read partition table before --setrw takes effect
+    # if [ ${bdverbose} ] ; then
+        # echo blockdev --rereadpt ${bdverbose} $1
+    # fi
+    # blockdev --rereadpt ${bdverbose} $1
 else
     echo "option --set ${swp} is invalid"
     exit 1
